name: dbt CI

on:
  push:
    branches: [ main, development ]
  pull_request:
    branches: [ main, development ]

jobs:
  dbt-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install dbt-snowflake==1.6.0
        pip install sqlfluff==2.3.0
        dbt deps
    
    - name: Run dbt compilation
      run: |
        dbt compile --profiles-dir ./profiles
      env:
        DBT_PROFILES_DIR: ./profiles
    
    - name: Run SQL linting
      run: |
        sqlfluff lint models/
    
    - name: Run dbt tests
      if: github.event_name == 'pull_request'
      run: |
        dbt test --profiles-dir ./profiles --select state:modified
      env:
        DBT_PROFILES_DIR: ./profiles