version: '3.8'

services:
  # MongoDB service
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
  
  # Backend service
  backend:
    build: ./backend
    container_name: todo-backend
    restart: always
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongodb:27017/todo-app
      - JWT_SECRET=your_jwt_secret_key_change_in_production
      - NODE_ENV=development
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    networks:
      - app-network
  
  # Frontend service
  frontend:
    build: ./frontend
    container_name: todo-frontend
    restart: always
    environment:
      - VITE_API_URL=http://localhost:5000/api
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - app-network

# Networks
networks:
  app-network:
    driver: bridge

# Volumes
volumes:
  mongodb_data: